export const CURRENT_USER  = 'CURRENT_USER ';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const POST_BUSINESS = 'POST_BUSINESS';
export const GET_ALL_BUSINESS = 'GET_ALL_BUSINESS';
export const GET_SINGLE_BUSINESS = 'GET_SINGLE_BUSINESS';
